# Exercícios

**Exercício**

Crie um *array* numpy de uma dimensão, com números de $0$ a $9$.

Saída:
```py
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

**Exercício**

Crie um *array* numpy de ordem 5x5 somente com valores `True`.

Saída:
```
array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])
```

**Exercício**

Crie um *array* numpy com valores aleatórios. Em seguida, mostre apenas os valores ímpares presentes no *array*.

**Exercício**

Crie um *array* numpy com valores de 1 a 19. Em seguida, substitua todos os valores pares por -1.

**Exercício**

Crie um *array* com posições de 0 a 9, e transforme-o em um array com os valores organizados em duas colunas.

Saída:
```
array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])
```


**Exercício**

Crie um array com posições de 0 a 9, e transforme-o em um array com os valores organizados em uma única coluna.

Saída:
```
array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])
```

**Exercício**

Transforme os arrays `x`e `y`
```python
x = np.array([1, 3, 5, 7, 8, 6, 4, 2, 0, 11])
y = np.array([2, 4, 6, 8, 7, 5, 3, 1, 0, 12])
```
em um array de duas dimensões, concatenando-os verticalmente em duas colunas.

Saída:
```python
array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [8, 7],
       [6, 5],
       [4, 3],
       [2, 1],
       [0, 0],
       [11, 12]])
```



**Exercício**

Crie um *array* numpy com valores de 100 a 200, de forma que a diferença entre cada elemento seja 10.

**Exemplo** 

- Saída:
```
array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190])
```

## Referências

[PRABHAKARAN, S. 101 NumPy Exercises for Data Analysis (Python). Machine Learning Plus, 2018.](https://www.machinelearningplus.com/python/101-numpy-exercises-python/)

[ROUGIER, N. P. 100 numpy exercises.](https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb)