# Numpy

Numpy é uma biblioteca Python voltada para computação científica.

## Importação

Para importar a biblioteca, utilize
```py
import numpy as np
```
`np` é o nome dado que utilizaremos para acessar a biblioteca.

In [2]:
import numpy as np

## *Arrays*
O *array* numpy é uma lista de valores, indexada por uma tupla de inteiros não negativos. O número de dimensões do array é o *rank* do array. O *shape* de um *array* é uma tupla de inteiros, dado o tamanho do *array* em cada dimensão definida.

**Exemplo**

Crie um vetor de uma dimensão
```py
a = np.array([1, 2, 3])
```

Observe o tipo do dado armazenado em cada posição
```py
print(type(a))
```

Observe o formato do vetor
```py
print (a.shape)
```

Mostra os elementos em cada posição
```py
print(a[0], a[1], a[2])
```

Mostra todo o vetor
```py
print(a)
```

Altera valor em uma posição
```py
a[0]=100
```

Mostra todo o vetor
```py
print(a)
```

**Atividade**

Crie um outro vetor, com o seguinte formato  
```py
b = np.array([[1,2,3], [4,5,6]])
```

Compare os vetores `a` e `b`. Qual é a diferença?

**Atividade**

Faça:  
```py
print(b[1])
print(b[1][1])
```

Explique o quê é mostrado

## *Reshape*
É possível alterar o formato do *array*. Execute os código abaixo passo a passo, observando o resultado:
```
arr = np.arange(10)
print(arr)
print(arr.shape)
arr.reshape(5,2)
arr.reshape(2,5)
```
**Sintaxe**

`.reshape(l,c)`  
onde:
- `l`: número de linhas
- `c`: número de colunas

O valor `l*c` deve corresponder à quantidade total de elementos no *array*.

In [3]:
arr = np.arange(10)

In [8]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
print(arr.shape)

(10,)


In [10]:
arr.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [15]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

É possível definir a ordem do *array* sem conhecer uma de suas dimensões. Para isto, para substituir o número de linhas ou colunas por `-1`.
**Exemplo**

```py
arr = np.arange(10)
arr.reshape(5,-1)
arr.reshape(-1,5)
arr.reshape(2,-1)
arr.reshape(-1,2)
```

In [17]:
arr = np.arange(10)

In [22]:
arr.reshape(-1,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

**Atividade**

Crie um *array* com 100 elementos contendo inteiros em sequência. Em seguida, organize esses valores em 10 colunas.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

## Tipos de dados

*Observe os tipos de dados armazenados*  
```py
print(a.dtype)
```

Compare com os tipos de dados destes outros vetores, e observe o que ocorre
```py
x=np.array([1, 2])
y=np.array([1.0, 2.0])
z=np.array([1, 2], dtype=np.int64)
```

## Funções para criação de arrays

Teste as funções abaixo, e observe o vetor retornado por cada função.
```py
np.zeros((2,2))
np.ones((3,3))
np.full((4,4),9)
np.eye(5)
np.random.random((6,6))
```

Outras funções podem ser utilizadas para obter valores igualmente espaçados entre si.
```py
np.linspace(0,10,5)
np.linspace(0,10,3)
np.linspace(0,10,11)
```
**Sintaxe**

```py
.linspace(i,f,n)
```
Onde:
- `i`: valor inicial
- `f`: valor final
- `n`: quantidade de valores
No método `linspace`, os valores de saída são do tipo `float` (`numpy.float64`).

In [36]:
type(np.linspace(0,10,11)[0])

numpy.float64

## *Slicing*

Semelhantes às listas em Python, os arrays numpy possibilitam o *slicing*. Como os arrays podem possuir diversas dimensões, é necessário identificar o *slice* para cada dimensão.  
```py
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, 1:3]
```

Significado:
```py
:2: linhas 0 a 1  
1:3: colunas 1 a 2
```

Observe o conteúdo dos vetores `a` e `b`.



Como seria para mostrar apenas determinadas colunas utilizando *slices*?

Execute os comandos abaixo, e discorra sobre os resultados
```py
b = a[[0,2], 2]  
c = a[[0,2,2], [0,2,3]]
```

O que ocorreu em `b` e `c`?

## Alterações em *slices*

**Atividade**

- Observe o array `a`
- Execute:
```py
c = a[:2, 1:3]
```
- Observe o array `c`
- Execute:
```py
c[0][0]=20
```
- Observe o array a

O que ocorreu?  

**Atividade**

O que ocorre com as operações abaixo?
```py
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
b = np.array(0, 2, 0, 1)
```
Explique o resultado ocorrido.
